name: Environment Variable Error

# on:
#   push:
#     branches:
#       - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Access missing environment variable
        run: echo $MISSING_VARIABLE